(function(root){
 const same=(a,b)=>a.length===b.length&&a.every(x=>b.includes(x));
 function empty(c){return {step:0,entities:[],attrs:{},keys:{},identifications:{},relations:{},associationChoices:[],associationsConfirmed:false,tables:{},quiz:{},passed:[],assisted:[],hints:{},completed:false};}
 function check(c,s,step){const issues=[];const add=(msg)=>issues.push(msg);
 if(step===0){for(const e of c.entities)if(!s.entities.includes(e.id))add(`${e.name}: ${e.why}`);for(const id of s.entities){const d=c.distractors.find(x=>x.id===id);if(d)add(`${d.name}: ${d.why}`);}}
 if(step===1){issues.push(...checkIdentifications(c,s).issues);for(const e of c.entities){const selected=s.attrs[e.id]||[];for(const name of c.attrs[e.id])if(!selected.includes(name))add(`${e.name}: manca l’attributo ${name}.`);for(const name of selected)if(!c.attrs[e.id].includes(name))add(`${e.name}: ${e.attrs.find(a=>a.id===name)?.why||name+' non è richiesto dalla traccia.'}`);if(!same(s.keys[e.id]||[],e.key))add(`${e.name}: ${e.weak?'la parte locale della chiave è':'la chiave prevista è'} ${e.key.join(' + ')}.${e.weak?' L’identificatore completo comprende anche il padre.':' I valori descrittivi possono ripetersi.'}`);}}
 if(step===2){issues.push(...checkAssociations(c,s).issues);for(const r of c.relations){const v=s.relations[r.id]||{};const reversed=r.from!==r.to&&v.from===r.to&&v.to===r.from;if(!reversed&&(v.from!==r.from||v.to!==r.to))add(`${r.verb}: collega ${c.entities.find(e=>e.id===r.from).name} e ${c.entities.find(e=>e.id===r.to).name}${r.from===r.to?' in due ruoli diversi':''}.`);if(v.a!==(reversed?r.b:r.a)||v.b!==(reversed?r.a:r.b))add(`${r.verb}: ${r.why}`);}}
 if(step===3){for(const expected of c.tables){const actual=s.tables[expected.name];if(!actual){add(`Manca la tabella ${expected.name}.`);continue;}for(const col of expected.cols){const v=actual[col.name];if(!v){add(`${expected.name}: manca ${col.name}.`);continue;}if(!!v.pk!==col.pk)add(`${expected.name}.${col.name}: ${col.pk?'fa parte della PK':'non fa parte della PK'}.`);if((v.fk||'')!==col.fk)add(`${expected.name}.${col.name}: ${col.fk?'la FK deve riferire '+col.fk:'non è una FK'}.`);if(col.required&&!v.required&&!v.pk)add(`${expected.name}.${col.name}: la partecipazione è obbligatoria, serve NOT NULL.`);if(col.unique&&!v.unique&&!v.pk)add(`${expected.name}.${col.name}: serve UNIQUE per conservare il massimo 1.`);if(!col.unique&&(!col.pk||expected.cols.filter(x=>x.pk).length>1)&&v.unique)add(`${expected.name}.${col.name}: UNIQUE escluderebbe ripetizioni ammesse dalla traccia.`);if(!col.required&&!col.pk&&v.required&&col.fk)add(`${expected.name}.${col.name}: la FK deve ammettere NULL perché la partecipazione è facoltativa.`);}for(const name of Object.keys(actual))if(!expected.cols.some(x=>x.name===name))add(`${expected.name}.${name}: questa colonna non appartiene alla soluzione guidata. ${name.startsWith('Lista')?'I collegamenti multipli richiedono righe, non liste in una cella.':''}`);}for(const name of Object.keys(s.tables))if(!c.tables.some(t=>t.name===name))add(`${name}: questa tabella non serve nella conversione guidata. ${c.type==='1:N'?'Basta una FK sul lato N.':''}`);}
 if(step===4){for(const [i,q] of c.questions.entries()){if(s.quiz[i]!==q.correct)add(q.why);}}
 return {ok:issues.length===0,issues};}
 function solve(c,s,step){if(step===0)s.entities=c.entities.map(e=>e.id);if(step===1)for(const e of c.entities){s.attrs[e.id]=[...c.attrs[e.id]];s.keys[e.id]=[...e.key];s.identifications[e.id]={kind:e.weak?'dependent':'autonomous',owner:c.identifyingParents?.[e.id]||''};}if(step===2){s.associationChoices=c.relations.map(r=>r.id);s.associationsConfirmed=true;for(const r of c.relations)s.relations[r.id]={from:r.from,to:r.to,a:r.a,b:r.b};}if(step===3){s.tables={};for(const t of c.tables){s.tables[t.name]={};for(const col of t.cols)s.tables[t.name][col.name]={pk:col.pk,fk:col.fk,required:col.required,unique:col.unique};}}if(step===4)c.questions.forEach((q,i)=>s.quiz[i]=q.correct);return s;}
 // Cardinalità ai due estremi: il massimo dei legami di A è sul lato B.
 function relationFields(v){const card=v.cardinality||((v.a&&v.b)?v.b.split(',')[1]+':'+v.a.split(',')[1]:''),pair=card.split(':');const maxA=v.maxA??(v.a?v.a.split(',')[1]:pair[1]||''),maxB=v.maxB??(v.b?v.b.split(',')[1]:pair[0]||'');return {cardinality:maxA&&maxB?maxB+':'+maxA:'',partA:v.partA??(v.a?v.a.split(',')[0]:''),partB:v.partB??(v.b?v.b.split(',')[0]:''),maxA,maxB};}
 function setRelation(v,prop,value){Object.assign(v,relationFields(v));v[prop]=value;if(prop==='cardinality'){const pair=value.split(':');v.maxA=pair[1]||'';v.maxB=pair[0]||'';}v.cardinality=v.maxA&&v.maxB?v.maxB+':'+v.maxA:'';v.a=v.partA!==''&&v.maxA?v.partA+','+v.maxA:'';v.b=v.partB!==''&&v.maxB?v.partB+','+v.maxB:'';return v;}
 function diagramRelation(r,v){const f=relationFields(v);const participation=n=>n==='1'?'required':n==='0'?'optional':'unset';const forward=v.from===r.from&&v.to===r.to,reverse=r.from!==r.to&&v.from===r.to&&v.to===r.from;return {top:['1','N'].includes(f.maxB)?f.maxB:'',bottom:['1','N'].includes(f.maxA)?f.maxA:'',partA:participation(f.partA),partB:participation(f.partB),direction:forward?'▼':reverse?'▲':''};}
 function checkAssociations(c,s){const selected=s.associationChoices||[],issues=[];for(const r of c.relations)if(!selected.includes(r.id))issues.push(`Manca un’associazione: cerca nella traccia come gli oggetti interagiscono. Rileggi le frasi prima di scegliere.`);for(const id of selected)if(!c.relations.some(r=>r.id===id)){const d=c.associationDistractors?.find(d=>d.id===id);issues.push(d?`${d.verb}: ${d.why}`:'Questa associazione non è prevista dalla traccia.');}return {ok:issues.length===0,issues:[...new Set(issues)]};}
 function restoreAssociations(c,s,raw){const candidates=[...c.relations,...c.associationDistractors||[]];if(Array.isArray(raw.associationChoices)){s.associationChoices=[...new Set(raw.associationChoices)].filter(id=>candidates.some(r=>r.id===id));s.associationsConfirmed=!!raw.associationsConfirmed&&checkAssociations(c,s).ok;}else if(Object.keys(raw.relations||{}).length||raw.passed?.includes(2)){s.associationChoices=c.relations.map(r=>r.id);s.associationsConfirmed=true;}return s;}
 function checkIdentifications(c,s){const issues=[];for(const e of c.entities){const v=s.identifications?.[e.id];if(!v?.kind){issues.push(`${e.name}: scegli come si identifica l’entità.`);continue;}if(e.weak){const owner=c.entities.find(n=>n.id===c.identifyingParents?.[e.id]);if(v.kind!=='dependent')issues.push(`${e.name}: ${e.key.join(' + ')} può ripetersi per oggetti diversi. La chiave completa comprende anche quella di ${owner.name}: l’entità è debole.`);else if(v.owner!==owner.id)issues.push(`${e.name}: per distinguere le istanze serve anche la chiave di ${owner.name}.`);}else if(v.kind!=='autonomous')issues.push(`${e.name}: ${e.key.join(' + ')} identifica già ogni istanza. Un’associazione obbligatoria non rende automaticamente debole un’entità.`);}return {ok:issues.length===0,issues};}
 function restoreIdentifications(c,s,raw){for(const e of c.entities){const v=raw.identifications?.[e.id];if(v&&['autonomous','dependent'].includes(v.kind))s.identifications[e.id]={kind:v.kind,owner:v.kind==='dependent'&&c.entities.some(n=>n.id===v.owner&&n.id!==e.id)?v.owner:''};}return s;}
 const API={same,empty,check,solve,relationFields,setRelation,diagramRelation,checkAssociations,restoreAssociations,checkIdentifications,restoreIdentifications};if(typeof module!=='undefined')module.exports=API;root.ER=API;
})(typeof window!=='undefined'?window:globalThis);
